quotes = [
	"Oh, my fuck!",
	"I'm tellin' ya, tonight, I am getting drunk at Julian's and it's going to be awesome.",
	"Gimme your smokes, man!",
	"Smokes, let's go, give me some smokes.",
	"I've got work to do.",
	"You can't tell me to do that. It's like telling the NWA to stop being black.",
	"Get two birds stoned at once.",
	"Make like a tree and fuck off.",
	"You're prostituting yourself out for cheeseburgers again, aren't you?",
	"A man's gotta eat.",
	"Birds of a shitfeather flock together.",
	"The liquor works for both sides, buddy.",
	"Peanut butter and jaaaaaaaaaaam!",
	"Green eggs and haaaaaaaaaaam!",
	"Baaaaaaaaaaam!",
	"Ya know what I'm sayin'? ",
	"Fuck, that's good pepperoni!",
	"Does the Tin Man have a sheet-metal cock?",
	"I mean, nobody wants to admit they ate nine cans of ravioli, but I did. I'm ashamed of myself.",
	"What, do you own space? No, NASA does.",
	"Why aren't you watching the dope plants, you asshole?",
	"Give me the cat back.",
	"Hey, you owe me you fuckin' greasy caveman!",
	"The 'J' is silent.",
	"The liquor feels like a familiar pair of slippers that you put on and sit in front of the fire.",
	"This here's my shed, right here. I've been living in these most of my life.",
	"I am the liquor.",
	"Like a shit-hawk.",
	"Shit-snares, Randy...",
	"Do you feel that, Randy, the way the shit clings to the air? Shit Blizzard.",
	"I will make you have an eternity test if I have to.",
	"Unleaded tastes a little tangy. Supreme is kinda sour, and diesel tastes pretty good.",
	"Friends of the road, buddy.",
	"That's the way she goes.",
	"The liquor feels like a familiar pair of slippers that you put on and sit in front of the fire.",
	"There's something you forgot about. The liquor works for both sides buddy.",
	"Unleaded tastes a little tangy. Supreme is kinda sour, and diesel tastes pretty good.",
	"You could teach living in a car and growing dope 101.",
	"This here's my shed, right here. I've been living in these most of my life.",
	"The old shit clock's ticking...",
	"We're about to sail into a shit typhoon.",
	"I am drunk as fuck.",
	"Me, him and you split it 50-50-50.",
	"Chicken and bangin, that's nice.",
	"I'm watching you, Julian. Like a shit-hawk.",
	"Shit-snares, Randy...",
	"Save me some of those sweet 'n' powered chicken things.",
	"I will make you have an eternity test if I have to.",
	"You... Mustard Tiger!",
	"Friends of the road, buddy."
]